-- Differential test: strudel-lua vs REAL Strudel on test/cases.txt (golden.json is generated by
-- reference/gen.mjs). Compares the onset events of cycles 0..8: exact rational times, values with 1e-9 tolerance.
local here = (arg and arg[0] or ""):match("^(.*)/test/[^/]*$") or "."
package.path = here .. "/src/?.lua;" .. here .. "/test/?.lua;" .. package.path
local J = require("json")
local Strudel = require("strudel")
local P = Strudel.Pattern

local f = assert(io.open(here .. "/test/golden.json", "rb"))
local golden = J.decode(f:read("a")); f:close()

local function same(a, b)
  if type(a) == "number" and type(b) == "number" then
    return math.abs(a - b) <= 1e-9 * math.max(1, math.abs(a), math.abs(b))
  end
  if type(a) ~= type(b) then return false end
  if type(a) ~= "table" then return a == b end
  -- (non-string keys are hidden bookkeeping such as the scale name, Strudel keeps those in hap.context)
  for k, v in pairs(a) do if type(k) == "string" and not same(v, b[k]) then return false end end
  for k in pairs(b) do if a[k] == nil then return false end end
  return true
end

local verbose = arg and arg[1] == "-v"
local pass, fail, skipped = 0, 0, 0
local failures = {}
for _, case in ipairs(golden) do
  if case.error then
    skipped = skipped + 1
  else
    local r, err = Strudel.run(case.src)
    local ok, why = true, nil
    if not r then
      if #case.events == 0 then ok = true else ok, why = false, "error: " .. tostring(err) end
    else
      local pat = r.layers[1] and r.layers[1].pattern
      if not pat then ok, why = false, "no pattern"
      else
        local okq, evs = pcall(Strudel.events, pat, 0, 8)
        if not okq then
          -- real Strudel logs query errors and returns no events; count "both fail" as equivalent
          if #case.events == 0 then ok, why = true, nil else ok, why = false, "query error: " .. tostring(evs) end
        else
          local used = {}
          local mine = {}
          for _, e in ipairs(evs) do mine[#mine + 1] = { b = tostring(e.b), e = tostring(e.e), v = e.value } end
          if #mine ~= #case.events then
            ok, why = false, string.format("event count %d, Strudel has %d", #mine, #case.events)
          else
            for _, want in ipairs(case.events) do
              local found
              for i, got in ipairs(mine) do
                if not used[i] and got.b == want.b and got.e == want.e and same(got.v, want.v) then found = i; break end
              end
              if not found then
                ok, why = false, string.format("no match for event %s..%s value %s", want.b, want.e,
                  require("reference_lib").ser(want.v))
                break
              end
              used[found] = true
            end
          end
        end
      end
    end
    if ok then pass = pass + 1 else fail = fail + 1; failures[#failures + 1] = case.src .. "\n      " .. why end
  end
end
for i, m in ipairs(failures) do if verbose or i <= 40 then print("FAIL: " .. m) end end
print(string.format("reference: %d identical to Strudel, %d different, %d rejected by Strudel itself", pass, fail, skipped))
os.exit(fail == 0 and 0 or 1)
