// Writes ../src/strudel/scales.lua from tonal's scale dictionary (same data real Strudel uses).
import fs from 'node:fs';
import { ScaleType } from '@tonaljs/tonal';
const rows = ScaleType.all().map((s) => ({ name: s.name, aliases: s.aliases, intervals: s.intervals }));
const q = (x) => JSON.stringify(x);
let out = '-- strudel/scales.lua  (GENERATED by reference/gen_scales.mjs from the scale dictionary of tonal.js, MIT)\n';
out += '-- { name, { aliases }, { intervals } }\nreturn {\n';
for (const r of rows) {
  out += `  { ${q(r.name)}, { ${r.aliases.map(q).join(', ')} }, { ${r.intervals.map(q).join(', ')} } },\n`;
}
out += '}\n';
fs.writeFileSync(new URL('../src/strudel/scales.lua', import.meta.url), out);
console.log('scales:', rows.length);
